#!/usr/bin/perl -w
use strict;
use lib qw( lib ../lib );
use lib qw( extlib ../extlib );
use lib qw( plugins/Remtter/lib plugins/Remtter/extlib );

use MT;

my $app = MT->instance;
if ( my $plugin = MT->component( 'Remtter' ) ) {
    require Remtter::Tasks;
    Remtter::Tasks::remtter();
}

1;
